#!/bin/sh

if [[ -z "$1" ]]; then
	echo "Usage: wanok <option: http | ssh | ftp | [port num]>" > /dev/console
	exit
fi

for arg in "$@"
do

wanip="$(ifconfig | grep -A 1 'eth0.2' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)"

if [[ "$arg" == http ]]; then
	portnum=80
elif [[ "$arg" == ssh ]]; then
	portnum=22
elif [[ "$arg" == ftp ]]; then
	portnum=21
	if [[ -z "$(grep anonymous=YES /etc/vsftpd.conf)" ]]; then
		sed -i "s/anonymous_enable=NO/anonymous_enable=YES/g" /etc/vsftpd.conf
		mkdir -p /home/ftp
		/etc/init.d/vsftpd restart
	fi
else
	if [[ -z "${arg//[0-9]/}" ]]; then  # check number
		portnum=$arg
	else
		continue
	fi
fi

echo "iptables -I INPUT -p tcp -s 0.0.0.0/0 -d $wanip --dport $portnum -j ACCEPT" > /dev/console
iptables -I INPUT -p tcp -s 0.0.0.0/0 -d $wanip --dport $portnum -j ACCEPT

echo "iptables -I FORWARD -m tcp -p tcp -d $wanip --dport $portnum -j ACCEPT" > /dev/console
iptables -I FORWARD -m tcp -p tcp -d $wanip --dport $portnum -j ACCEPT

done
