#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=10
USE_PROCD=1

validate_system_section() {
	uci_load_validate system system "$1" "$2" \
		'hostname:string:OpenWrt' \
		'conloglevel:uinteger' \
		'buffersize:uinteger' \
		'timezone:string:UTC' \
		'zonename:string'
}

system_config() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	echo "PARKIS: /etc/init.d/system system_config" > /dev/console
	#PARKIS: change firewall
	sed -i "/option syn_flood/a \	option synflood_protect\	1" /etc/config/firewall
	sed -i "/option syn_flood/a \	option flow_offloading\	1" /etc/config/firewall
	sed -i "/option syn_flood/d" /etc/config/firewall

	#PARKIS: change hostname
	if [ $hostname != VX2000 ]; then
		sed -i "s/"$hostname"/VX2000/g" /etc/config/system
		hostname=VX2000
	fi
	echo "$hostname" > /proc/sys/kernel/hostname
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}

	echo "$timezone" > /tmp/TZ
	#PARKIS: change localtime
	[ -z "$(grep zonename /etc/config/system)" ] && [ -f "/usr/share/zoneinfo/Asia/Seoul" ] \
		&& sed -i "/hostname/a \	option zonename 'Asia/Seoul'" /etc/config/system \
		&& zonename="Asia/Seoul"
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/${zonename// /_}" ] \
		&& ln -sf "/usr/share/zoneinfo/${zonename// /_}" /tmp/localtime \
		&& rm -f /tmp/TZ

	# apply timezone to kernel
	date -k

	#PARKIS: add log file name
	[ -z "$(grep log_file /etc/config/system)" ] && sed -i "/log_size/a \	option log_file '/root/vtaircmd.log'" /etc/config/system
}

reload_service() {
	config_load system
	config_foreach validate_system_section system system_config
}

service_triggers() {
	procd_add_reload_trigger "system"
	procd_add_validation validate_system_section
}

start_service() {
	reload_service
}
